# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DODDLE-OWL | a Domain Ontology rapiD Development Environment - OWL extension
ja_title: DODDLE-OWL | a Domain Ontology rapiD Development Environment - OWL extension
email: morita [at] it.aoyama.ac.jp
description: DODDLE-OWL Web Site

# Build settings
markdown: kramdown
